apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: default  # Ensure the correct namespace is specified or default if no specific namespace is required
  labels:
    app: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: muyiwao/flask-api:latest
        ports:
        - name: ENDPOINT
          value: "${env.USER}"
        - name: USER
          value: "${env.PASSWORD}"
        - name: PASSWORD
          value: "${env.ENDPOINT}"
        - name: PORT
          value: "${env.PORT}"
        - name: DATABASE
          value: "${env.DATABASE}"
